[package]
name = "fead"
version = "0.1.0"
edition = "2021"

[dependencies]
html2text = "0.12.5"
htmlentity = "1.3.2"
quick-xml = "0.36"
reqwest = "0.12"
serde = { version = "1.0.208", features = ["derive"] }
serde-xml-rs = "0.6.0"
termimad = "0.30.0"
termion = "4.0.2"
tokio = { version = "1", features = ["full"] }
